### ISSUE TITLE
Move the controls above the phrase

### ISSUE THREAD

**Issue by J053Fabi0** [blmage/duolingo-tts-controls#111]
Sometimes I reach a word in the phrase and when I want to come back to write my answer I accidentally trigger the full control panel, which is a bit annoying.

My idea is that maybe the controls could be placed anywhere else, like above the phrase and buttons.

**Comment by blmage** [comment]
Thanks for the report!

This is an oversight on my part, as I'm usually the first to be annoyed when this happens with menus for example.

ef700f8471c52712d788e6e27abfb4b7e24aa192 adds a 200ms delay before the control panel is displayed.

Please reopen this issue if you feel this could/should be refined! (perhaps via customization options?)
