### ISSUE TITLE
Pop-out buttons are glitchy

### ISSUE THREAD

**Issue by Chirunos** [blmage/duolingo-tts-controls#117]
Chinese for English speakers. Firefox Release 105.0.1. I can't use any of the controls
![image](https://user-images.githubusercontent.com/85644671/192126356-2fb528fd-5054-4c46-b5b4-97612bf514cf.png)

**Comment by blmage** [comment]
Thanks for reminding me of this one. 

This should have been fixed a while ago, but somehow the fix had not been released everywhere yet - sorry! :confused:
