### ISSUE TITLE
Not working in "Listen and respond" exercises

### ISSUE THREAD

**Issue by xt1zer** [blmage/duolingo-tts-controls#93]
The controls don't show up in "Listen and respond" exercises. Using 1.2.9 in Firefox 82.0.2, Fedora 33.
![Screenshot_2020-11-08 Learn a language for free](https://user-images.githubusercontent.com/41012295/98464323-25261180-21d3-11eb-9423-55fad65797d2.png)

**Comment by blmage** [comment]
Thanks for the report! That's an oversight on my part.

Could you point me to the course/lesson in which you got this exercise? (I enabled speaking exercises, but couldn't find one yet)

**Comment by xt1zer** [comment]
Hey, sorry for the delay. It's in french course, and I can't really tell which lesson was it, must be one of the first 10 after checkpoint 2. They're quite rare, but you can get such exercise in several lessons.

**Comment by blmage** [comment]
Actually, there is another solution - when you get the same kind of challenge again, could you check in the UI if there is a `div` with a `data-test` attribute containing "`challenge`", and report the complete value here?

For example, "`challenge-completeReverseTranslation`" in this case:
![image](https://user-images.githubusercontent.com/25432517/99070463-8cb3d680-25b0-11eb-97bd-499b5ae23f5b.png)

Thanks!

**Comment by xt1zer** [comment]
Will do ASAP. Sadly, I haven't had this challenge again yet.

**Comment by blmage** [comment]
OK, no worries! (I couldn't get one myself after a few more tries)

Here are the types that are requested when I start a French session - I have a hunch that `listenComprehension` might be the one we are looking for, but that would need confirmation:
- `characterIntro`
- `characterMatch`
- `characterSelect`
- `completeReverseTranslation`
- `definition`
- `dialogue`
- `form`
- `freeResponse`
- `gapFill`
- `judge`
- `listen`
- `name`
- `listenComprehension`
- `listenTap`
- `readComprehension`
- `select`
- `selectPronunciation`
- `selectTranscription`
- `speak`
- `tapCloze`
- `tapClozeTable`
- `tapComplete`
- `tapCompleteTable`
- `tapDescribe`
- `translate`
- `typeCloze`
- `typeClozeTable`
- `typeCompleteTable`

**Comment by blmage** [comment]
This type of challenge is now (at last!) supported in version `2.0.0`.
