### ISSUE TITLE
controls overlap input field 

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-tts-controls#96]
I have animated characters blocked ...  may be that's why 
<img width="340" alt="Screen Shot 2020-12-02 at 18 32 16" src="https://user-images.githubusercontent.com/60418150/100867707-23e3be00-34cd-11eb-9a0b-be3cd3e71c3e.png">

**Comment by blmage** [comment]
Yes, when characters are visible there is enough space under the buttons - I'll see what we can do in this particular case.

**Comment by alexseyk** [comment]
may be put controls above ?

**Comment by alexseyk** [comment]
another issue : displaying controls below moves  2row words out of sight 

<img width="672" alt="Screen Shot 2020-12-04 at 17 14 12" src="https://user-images.githubusercontent.com/60418150/101151878-e5790b00-3654-11eb-9dc4-7da1bc0b4a2f.png">

 "bajo" es debajo :(
<img width="622" alt="Screen Shot 2020-12-04 at 17 15 28" src="https://user-images.githubusercontent.com/60418150/101151994-05103380-3655-11eb-8c0a-ca05a3ca00a7.png">

**Comment by blmage** [comment]
Which extension/user stylesheet do you use to hide the characters?

**Comment by alexseyk** [comment]
https://github.com/AdguardTeam/AdguardBrowserExtension

with rules 
www.duolingo.com##._1RL1c
www.duolingo.com##._2Dn_R
www.duolingo.com##.F2B9m

**Comment by Nudin** [comment]
Another similar issue:
![Bildschirmfoto zu 2021-03-17 23-20-40](https://user-images.githubusercontent.com/509205/115971626-cd455200-a549-11eb-99ea-c47339bda173.png)

**Comment by blmage** [comment]
@alexseyk The UI has been extensively reworked in version `2.0.0`, so this kind of problem should be much less likely to occur now!

@Nudin It seems that sometimes the FontAwesome styles are not properly injected in the pages, but I've had a hard time trying to reproduce this consistently so far. In any case, I've just created #109 to help keep track of this. Thanks for the report!
