### ISSUE TITLE
extended controls display position

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-tts-controls#97]
Would it be possible to display controls of normal speech to the left and slow speed speech to the left as it is ?
Imho it will avoid confusion.
 Is it possible to display both controls simultaneously to allow for fine tuning of playback speed ? 
for example 
![Screen Shot 2020-12-02 at 18 37 13](https://user-images.githubusercontent.com/60418150/100868268-fa776200-34cd-11eb-9b98-28322b9c7602.png)

**Comment by blmage** [comment]
Good idea! 

I'd like to avoid hiding elements from the UI though, so I'll try to find a satisfactory compromise.

Also, I'll have to find a way to make it clear on which form keyboard shortcuts are currently applied (unless the keyboard icon is sufficient).

**Comment by alexseyk** [comment]
I guess an active  keyboard icon should be enough. Perhaps you can use Tab to switch  between them.

**Comment by blmage** [comment]
Finally had enough time (and inspiration) to work on this - it is available in version `2.0.0`.

Thanks again for the suggestion! (I may be biased, but I really think the extension has become much more user-friendly now)
