### ISSUE TITLE
it does not work with new english from russian tree

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-tts-controls#99]
it does not work with new english from russian tree
but it works with the old one

**Comment by blmage** [comment]
Not sure if this is related, but after taking a look at the current A/B tests while working on the d'n'd extension, it appears that Duo intends to change its audio library. Maybe this is only taking place on new courses at the moment.

In any case, I'm going to have a hard time checking this on the tree you mentioned, so don't hesitate to point out if you could reproduce it on another one!

**Comment by alexseyk** [comment]
I was about to create a demo account for you when i found that  it works now

**Comment by alexseyk** [comment]
> it appears that Duo intends to change its audio library

seen this in Spanish tree : setting appear but not available and 1st time the audio played it is truncated
<img width="389" alt="Screen Shot 2020-12-05 at 01 45 54" src="https://user-images.githubusercontent.com/60418150/101203540-678d2200-369d-11eb-9e22-9ef3fc800bea.png">
